import type { Application, JobPost, User } from "../types";

export const mockUser: User = {
    id: "u1",
    name: "Samuel Tech",
    email: "samuel@example.com",
    role: "applicant",
    avatarUrl: "https://i.pravatar.cc/150?u=samuel",
    location: "Addis Ababa, Ethiopia",
    title: "Frontend Developer",
    trustScore: 92,
    profileCompletion: 80,
};

export const mockJobs: JobPost[] = [
    {
        id: "j1",
        title: "UI/UX Designer for Mobile App",
        company: "BoldTech Inc.",
        location: "Addis Ababa",
        salary: "$50/hr",
        type: "Full-time",
        level: "Intermediate",
        matchScore: 92,
        tags: ["Figma", "User Research", "Wireframing", "Prototyping"],
        datePosted: "10 min ago",
    },
    {
        id: "j2",
        title: "Frontend Developer for E-commerce Site",
        company: "ShopSphere Ltd.",
        location: "Remote",
        salary: "$150k - $210k",
        type: "Full-time",
        level: "Senior",
        matchScore: 88,
        tags: ["React", "Next.js", "Tailwind"],
        datePosted: "April 10, 2025",
    },
    {
        id: "j3",
        title: "Product Designer for SaaS Platform",
        company: "CloudNest Solutions",
        location: "Addis Ababa",
        salary: "$80k - $120k",
        type: "Full-time",
        level: "Intermediate",
        matchScore: 75,
        tags: ["UX Research", "Figma", "SaaS"],
        datePosted: "March 25, 2025",
    },
    {
        id: "j4",
        title: "Graphic Designer for Marketing Campaign",
        company: "Creative Minds Co.",
        location: "Remote",
        salary: "$40k - $60k",
        type: "Freelance",
        level: "Junior",
        matchScore: 60,
        tags: ["Illustrator", "Photoshop", "Branding"],
        datePosted: "April 5, 2025",
    },
    {
        id: "j5",
        title: "Frontend Developer for Fintech App",
        company: "FinanceHub Inc.",
        location: "Remote",
        salary: "$130k - $160k",
        type: "Full-time",
        level: "Senior",
        matchScore: 85,
        tags: ["TypeScript", "React", "State Management"],
        datePosted: "April 15, 2025",
    },
    {
        id: "j6",
        title: "Data Analyst for Retail Analytics",
        company: "Insightful Data Corp.",
        location: "Addis Ababa",
        salary: "$70k - $90k",
        type: "Full-time",
        level: "Junior",
        matchScore: 40,
        tags: ["SQL", "Python", "Tableau"],
        datePosted: "March 30, 2025",
    },
];

export const mockApplications: Application[] = [
    {
        id: "app-1",
        jobId: "j1",
        jobTitle: "UI/UX Designer for Mobile App",
        company: "BoldTech Inc.",
        dateApplied: "March 15, 2025",
        status: "Under Review",
        statusColor: "blue",
    },
    {
        id: "app-2",
        jobId: "j2",
        jobTitle: "Frontend Developer for E-commerce Site",
        company: "ShopSphere Ltd.",
        dateApplied: "April 10, 2025",
        status: "Interview Scheduled",
        statusColor: "green",
    },
    {
        id: "app-3",
        jobId: "j3",
        jobTitle: "Product Designer for SaaS Platform",
        company: "CloudNest Solutions",
        dateApplied: "March 25, 2025",
        status: "Pending",
        statusColor: "orange",
    },
    {
        id: "app-4",
        jobId: "j4",
        jobTitle: "Graphic Designer for Marketing Campaign",
        company: "Creative Minds Co.",
        dateApplied: "April 5, 2025",
        status: "Accepted",
        statusColor: "green",
    },
    {
        id: "app-5",
        jobId: "j5",
        jobTitle: "Frontend Developer for Fintech App",
        company: "FinanceHub Inc.",
        dateApplied: "April 15, 2025",
        status: "Accepted",
        statusColor: "green",
    },
    {
        id: "app-6",
        jobId: "j6",
        jobTitle: "Data Analyst for Retail Analytics",
        company: "Insightful Data Corp.",
        dateApplied: "March 30, 2025",
        status: "Rejected",
        statusColor: "red",
    },
];
